### PR TITLE
fix #17

### LINKED ISSUE #17: ConvertFromSGF does not handle upper case letters
The method is only designed for lower case letters. Games with large boards [use capital letters](http://www.red-bean.com/sgf/go.html#types).

> The first letter designates the column (left to right), the second the row (top to bottom). The upper left part of the board is used for smaller boards, e.g. letters "a"-"m" for 13*13.
> A pass move is shown as '[]' or alternatively as '[tt]' (only for boards <= 19x19), i.e. applications should be able to deal with both representations. '[tt]' is kept for compatibility with FF[3].
> Using lowercase letters only the maximum board size is 26x26.
> 
> In FF[4] it is possible to specify board sizes upto 52x52. In this case uppercase letters are used to represent points from 27-52, i.e. 'a'=1 ... 'z'=26 , 'A'=27 ... 'Z'=52

Example SGF:
```
(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]
SZ[37]HA[9]AB[dd][sd][Hd][ds][ss][Hs][dH][sH][HH]RE[W+228.50]
;W[]
;B[II]
;W[]
;B[uJ]
;W[tJ])
```

https://github.com/paviad/GoSharp/blob/4f9a889cce629df6040a8c7e848ad74634f6a331/Point.cs#L80-L85

### PR DESCRIPTION
**Pull request by nerai**

### CODE REVIEW

**Comment by nerai** [comment]
The original code only handled lowercase letters. Uppercase letters got converted to negative indexes (since 'A' < 'a'). According to the spec, 'A' should map to one behind 'z'.

The patch checks which case is present. If lower, it converts the same way as before. If upper, it converts 'A' to index 26, which is 'z'-'a'+1, and so on.

**Comment by paviad** [comment]
'a' should be converted to 0 while same as 'A' but in your code 'A' will be converted to 26, or am I reading this wrong?

**Comment by nerai** [comment]
'a' should convert to 0, yes. 'A' should convert to one behind 'z':

> Using lowercase letters only the maximum board size is 26x26.
> 
> In FF[4] it is possible to specify board sizes upto 52x52. In this case uppercase letters are used to represent points from 27-52, i.e. 'a'=1 ... 'z'=26 , 'A'=27 ... 'Z'=52

(The code is zero-based, so it is one less in either case than described in the spec.)

**Comment by paviad** [comment]
I'm sorry, I have forgotten the standard :) :+1:

**Pull request merged**
